import type { MarketingStore } from "./types";

export const DEFAULT_MARKETING_STORE: MarketingStore = {
  pricing: {
    currency: "USD",
    yearlyDiscountPercent: 20,
    publishedAt: new Date().toISOString(),
    draft: false,
    plans: [
      {
        planId: "trial",
        planName: "Free Trial",
        description: "Evaluate the full platform with production-grade voice AI.",
        monthlyPrice: 0,
        yearlyPrice: 0,
        currency: "USD",
        isPopular: false,
        isVisible: true,
        isEnterprise: false,
        trialEnabled: true,
        trialDays: 14,
        features: [
          "100 call minutes included",
          "1 AI voice agent",
          "1 phone number",
          "Call recordings & transcripts",
          "Basic analytics",
          "Email support",
        ],
        limits: {
          callMinutes: 100,
          aiAgents: 1,
          phoneNumbers: 1,
          campaigns: 1,
          teamMembers: 1,
          providerConnections: 1,
        },
        overageRates: [],
        addOns: [],
        ctaLabel: "Start free trial",
        ctaUrl: "/register?plan=trial",
        sortOrder: 0,
      },
      {
        planId: "starter",
        planName: "Starter",
        description: "For small teams launching their first AI calling workflows.",
        monthlyPrice: 49,
        yearlyPrice: 470,
        currency: "USD",
        isPopular: false,
        isVisible: true,
        isEnterprise: false,
        trialEnabled: true,
        trialDays: 14,
        features: [
          "500 call minutes / month",
          "Up to 3 AI agents",
          "2 phone numbers",
          "Inbound & outbound calling",
          "Call logs & transcripts",
          "Basic analytics",
        ],
        limits: {
          callMinutes: 500,
          aiAgents: 3,
          phoneNumbers: 2,
          campaigns: 3,
          teamMembers: 2,
          providerConnections: 2,
        },
        overageRates: [
          { label: "Extra minutes", unit: "minute", pricePerUnit: 0.12 },
        ],
        addOns: [
          {
            id: "extra-minutes-500",
            name: "+500 minutes",
            description: "Additional call minute bundle",
            monthlyPrice: 45,
          },
        ],
        ctaLabel: "Start trial",
        ctaUrl: "/register?plan=starter",
        sortOrder: 1,
        backendTier: "starter",
      },
      {
        planId: "growth",
        planName: "Growth",
        description: "Scale outbound campaigns and multi-agent operations.",
        monthlyPrice: 149,
        yearlyPrice: 1430,
        currency: "USD",
        isPopular: true,
        isVisible: true,
        isEnterprise: false,
        trialEnabled: true,
        trialDays: 14,
        features: [
          "2,000 call minutes / month",
          "Up to 10 AI agents",
          "5 phone numbers",
          "Campaign automation",
          "Knowledge base & tools",
          "Advanced analytics",
          "Priority support",
        ],
        limits: {
          callMinutes: 2000,
          aiAgents: 10,
          phoneNumbers: 5,
          campaigns: 10,
          teamMembers: 5,
          providerConnections: 5,
        },
        overageRates: [
          { label: "Extra minutes", unit: "minute", pricePerUnit: 0.09 },
        ],
        addOns: [
          {
            id: "extra-agents-5",
            name: "+5 AI agents",
            description: "Expand concurrent agent capacity",
            monthlyPrice: 79,
          },
        ],
        ctaLabel: "Start trial",
        ctaUrl: "/register?plan=growth",
        sortOrder: 2,
        backendTier: "growth",
      },
      {
        planId: "scale",
        planName: "Scale",
        description: "High-volume teams running voice AI across departments.",
        monthlyPrice: 499,
        yearlyPrice: 4790,
        currency: "USD",
        isPopular: false,
        isVisible: true,
        isEnterprise: false,
        trialEnabled: false,
        trialDays: 0,
        features: [
          "10,000 call minutes / month",
          "Up to 50 AI agents",
          "20 phone numbers",
          "Unlimited campaigns",
          "Team roles & permissions",
          "Webhooks & API access",
          "Dedicated support",
        ],
        limits: {
          callMinutes: 10000,
          aiAgents: 50,
          phoneNumbers: 20,
          campaigns: 100,
          teamMembers: 25,
          providerConnections: 10,
        },
        overageRates: [
          { label: "Extra minutes", unit: "minute", pricePerUnit: 0.07 },
        ],
        addOns: [],
        ctaLabel: "Get Scale",
        ctaUrl: "/register?plan=scale",
        sortOrder: 3,
        backendTier: "pro",
      },
      {
        planId: "enterprise",
        planName: "Enterprise",
        description: "Custom limits, SSO, compliance packages, and dedicated infrastructure.",
        monthlyPrice: 0,
        yearlyPrice: 0,
        currency: "USD",
        isPopular: false,
        isVisible: true,
        isEnterprise: true,
        trialEnabled: false,
        trialDays: 0,
        features: [
          "Unlimited scale (custom)",
          "Dedicated account manager",
          "SSO & SAML",
          "Custom SLAs",
          "SOC 2 & GDPR packages",
          "Private deployment options",
          "Custom provider integrations",
        ],
        limits: {
          callMinutes: 999999,
          aiAgents: 999,
          phoneNumbers: 999,
          campaigns: 999,
          teamMembers: 999,
          providerConnections: 999,
        },
        overageRates: [],
        addOns: [],
        ctaLabel: "Contact sales",
        ctaUrl: "/contact",
        sortOrder: 4,
      },
    ],
  },
  content: {
    hero: {
      badge: "AI Voice Infrastructure Platform",
      headline: "AI Voice Agents That Call, Answer, Qualify, and Convert at Scale",
      subheadline:
        "Connect your phone providers, create intelligent voice agents, automate inbound and outbound calls, and manage every conversation from one multi-tenant SaaS platform.",
      primaryCta: "Start Free Trial",
      primaryCtaUrl: "/register",
      secondaryCta: "Book Demo",
      secondaryCtaUrl: "/contact",
    },
    announcement: "New: Multi-provider telephony with Twilio, SIP, and custom trunks.",
    testimonials: [
      {
        id: "1",
        quote:
          "We replaced our entire inbound qualification team with AI agents in two weeks. Call quality is indistinguishable from human reps.",
        author: "Sarah Chen",
        role: "VP Operations",
        company: "ScaleFlow SaaS",
      },
      {
        id: "2",
        quote:
          "Connecting Twilio numbers and launching outbound campaigns took hours, not months. The analytics alone paid for the platform.",
        author: "Marcus Webb",
        role: "Head of Sales",
        company: "Northline Insurance",
      },
      {
        id: "3",
        quote:
          "Tenant isolation and audit logs gave our enterprise clients the confidence to deploy voice AI at scale.",
        author: "Priya Sharma",
        role: "CTO",
        company: "VoiceStack Partners",
      },
    ],
    faqs: [
      {
        id: "1",
        category: "Product",
        question: "How do AI voice agents work?",
        answer:
          "You configure an agent with instructions, voice, and tools. When a call connects, the agent listens, reasons, and responds in real time using speech-to-text, LLM, and text-to-speech — handling qualification, booking, support, and more.",
      },
      {
        id: "2",
        category: "Providers",
        question: "Which phone providers are supported?",
        answer:
          "Twilio, TelephonyX-style SIP trunks, Vonage, Telnyx, and custom BYO SIP providers. Connect numbers you own or provision new ones through supported carriers.",
      },
      {
        id: "3",
        category: "Pricing",
        question: "Is there a free trial?",
        answer:
          "Yes. Start with a 14-day trial including call minutes, one agent, and full platform access. No credit card required for trial signup.",
      },
      {
        id: "4",
        category: "Security",
        question: "How is tenant data isolated?",
        answer:
          "Each workspace has isolated agents, numbers, calls, billing, and API keys. Platform admins cannot access tenant call content without audited impersonation.",
      },
      {
        id: "5",
        category: "Billing",
        question: "What happens if I exceed my plan limits?",
        answer:
          "Usage-based overage rates apply for extra call minutes. You'll receive warnings as you approach limits and can upgrade or purchase add-ons anytime.",
      },
    ],
    useCases: [
      {
        id: "sales",
        title: "Sales outreach",
        industry: "B2B Sales",
        problem: "SDRs spend hours on cold calls with low connect rates.",
        solution:
          "AI agents dial leads, handle objections, qualify interest, and book meetings automatically.",
        workflow: [
          "Upload lead list to campaign",
          "Agent calls with personalized opener",
          "Qualifies budget and timeline",
          "Books meeting on rep calendar",
        ],
        outcome: "3× more qualified meetings per rep, 60% lower cost per lead.",
      },
      {
        id: "support",
        title: "Customer support",
        industry: "SaaS & E-commerce",
        problem: "Support queues overflow during peak hours.",
        solution:
          "AI agents answer inbound calls, resolve common issues, and escalate complex cases.",
        workflow: [
          "Customer calls support line",
          "Agent identifies issue from knowledge base",
          "Resolves or creates ticket",
          "Sends follow-up summary",
        ],
        outcome: "40% reduction in hold times, 24/7 coverage without night shifts.",
      },
      {
        id: "healthcare",
        title: "Appointment reminders",
        industry: "Healthcare",
        problem: "No-shows cost clinics thousands monthly.",
        solution:
          "Outbound reminder calls confirm, reschedule, or cancel appointments conversationally.",
        workflow: [
          "Sync appointments from EHR/CRM",
          "Agent calls patient before visit",
          "Confirms or reschedules slot",
          "Updates calendar automatically",
        ],
        outcome: "28% fewer no-shows, improved patient satisfaction scores.",
      },
    ],
    integrations: [
      {
        id: "twilio",
        name: "Twilio",
        category: "Telephony",
        description: "Import numbers and route calls through your Twilio account.",
        status: "available",
      },
      {
        id: "telephonyx",
        name: "TelephonyX",
        category: "Telephony",
        description: "Connect TelephonyX SIP trunks for global number coverage.",
        status: "available",
      },
      {
        id: "sip",
        name: "SIP Trunk",
        category: "Telephony",
        description: "Bring your own SIP provider for custom telephony infrastructure.",
        status: "available",
      },
      {
        id: "webhooks",
        name: "Webhooks",
        category: "Developer",
        description: "Real-time events for calls, agents, and billing.",
        status: "available",
      },
      {
        id: "zapier",
        name: "Zapier",
        category: "Automation",
        description: "Connect to 5,000+ apps without code.",
        status: "coming_soon",
      },
    ],
    resources: [
      {
        id: "1",
        title: "The Complete Guide to AI Outbound Calling",
        excerpt:
          "Best practices for scripts, compliance, and conversion optimization.",
        category: "guide",
        date: "2026-06-15",
        readTime: "12 min",
      },
      {
        id: "2",
        title: "How Northline Cut Support Costs 40%",
        excerpt: "Case study on deploying AI agents for tier-1 support.",
        category: "case-study",
        date: "2026-05-28",
        readTime: "8 min",
      },
      {
        id: "3",
        title: "Multi-Tenant Voice AI Architecture",
        excerpt: "Technical deep dive on workspace isolation and provider routing.",
        category: "best-practice",
        date: "2026-05-10",
        readTime: "15 min",
      },
    ],
    seo: {
      defaultTitle: "VoxaAI — AI Voice Agent Platform",
      defaultDescription:
        "Deploy AI phone agents for inbound and outbound calls. Multi-provider telephony, campaigns, analytics, and enterprise multi-tenant workspaces.",
    },
  },
};

export const STORAGE_KEY = "voxaai-marketing-store-v1";
